name: native_app
description: >
  A command line application that can be compiled to native code using
  dart2native.
# This example isn't intended for publishing on pub.dev.
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dev_dependencies:
  galileo_mysql: ^3.0.0
  http: ^0.13.4

assets:
  - assets/